#!/bin/bash

readonly PROG_PATH=${0}
readonly PROG_DIR=${0%/*}
readonly PROG_NAME=$(basename $0)

notify() {
    echo "${PROG_NAME}: $1"
    return 0
}

print_usage() {

    echo "Usage: ${PROG_NAME}"

    return 0
}

main() {

    if [ "${1}" == "-h" ] || [ "${1}" == "--help" ]; then
	print_usage
	return 0
    fi
    echo "" >> .gitignore
    echo "### agi ###" >> .gitignore
    echo ".DS_Store" >> .gitignore
    echo "*~" >> .gitignore
    echo "\#*\#" >> .gitignore

    return 0
}

main "${@}"

