#!/bin/bash

readonly PROG_PATH=${0}
readonly PROG_DIR=${0%/*}
readonly PROG_NAME=$(basename $0)

notify() {
    echo "${PROG_NAME}: $1"
    return 0
}

print_usage() {

    echo "Usage: ${PROG_NAME} [options...]"
    echo
    echo "Options:"
    echo " -r, <file>         Requirements file installed after activation"

    return 0
}

main() {

    declare -ri NUM_ARGS=0

    if [ "${1}" == "-h" ] || [ "${1}" == "--help" ]; then
	print_usage
	return 0
    fi

    if [ $# -lt ${NUM_ARGS} ]; then 
	notify "try '${PROG_NAME} -h' or '${PROG_NAME} --help' for more information"
	return 1
    fi

    declare HAS_R_FLAG="false"
    declare R_FLAG=""

    declare -i I=$NUM_ARGS
    I=I+1
    while [ $I -le $# ]; do
	case ${!I} in
	    "-r")
		I=I+1
		HAS_R_FLAG="true"
		R_FLAG=${!I}
		;;
	    *)
		notify "${!I} does not match any supported option"
		;;
	esac
	I=I+1
    done

    if [ ! -d ".venv" ]; then
	mkdir .venv
	notify "created .venv folder"
    else
	notify ".venv folder already exists"
    fi
    
    python3 -m venv .venv
    notify "made .venv into virtual environment folder"

    if [ $? -ne 0 ]; then
	notify "python3 is not installed"
	return 1
    fi

    if [ "${HAS_R_FLAG}" == "true" ]; then
	source .venv/bin/activate
	notify "installing requirements..."
	python3 -m pip install -r "${R_FLAG}"
	notify "requirements installed!"
	deactivate
    else
	notify "-r flag is missing, no requirements installed"
    fi

    return 0
}

main "${@}"
