#!/bin/bash

readonly PROG_PATH=${0}
readonly PROG_DIR=${0%/*}
readonly PROG_NAME=$(basename $0)

notify() {
    echo "${PROG_NAME}: $1"
    return 0
}

print_usage() {

    echo "Usage: ${PROG_NAME} <file> [options...]"
    echo
    echo "Arguments:"
    echo " <file>             Purges the file from git history"
    echo
    echo "Options:"
    echo " -h,                Shows this help"

    return 0
}

main() {

    declare -ri NUM_ARGS=1

    if [ "${1}" == "-h" ] || [ "${1}" == "--help" ]; then
	print_usage
	return 0
    fi

    if [ $# -lt ${NUM_ARGS} ]; then 
	notify "try '${PROG_NAME} -h' or '${PROG_NAME} --help' for more information"
	return 1
    fi

#    if [ $# -le ${NUM_ARGS} ]; then 
#	notify "no default behaviour without any option(s)"
#	return 1
#    fi

    declare HAS_A_FLAG="false"
    declare A_FLAG=""

    declare -i I=$NUM_ARGS
    I=I+1
    while [ $I -le $# ]; do
	case ${!I} in
	    "-a")
		I=I+1
		HAS_A_FLAG="true"
		A_FLAG=${!I}
		;;
	    *)
		notify "${!I} does not match any supported option"
		;;
	esac
	I=I+1
    done

    declare FILE_ARG=${1}
    git filter-branch --force --index-filter "git rm --cached --ignore-unmatch ${FILE_ARG}" --prune-empty --tag-name-filter cat -- --all

    notify "Done! Now run a git push --force to sync to remote"

    return 0
}

main "${@}"

