#!/bin/bash

readonly PROG_PATH=${0}
readonly PROG_DIR=${0%/*}
readonly PROG_NAME=$(basename $0)

notify() {
    echo "${PROG_NAME}: $1"
    return 0
}

print_usage() {

    echo "Usage: ${PROG_NAME} [options...]"
    echo
    echo "Options:"
    echo " -r,                Resursive deletion with deletion prompts"

    return 0
}

main() {

    declare -ri NUM_ARGS=0

    if [ "${1}" == "-h" ] || [ "${1}" == "--help" ]; then
	print_usage
	return 0
    fi

    declare HAS_R_FLAG="false"

    declare -i I=$NUM_ARGS
    I=I+1
    while [ $I -le $# ]; do
	case ${!I} in
	    "-r")
		HAS_R_FLAG="true"
		;;
	    *)
		notify "${!I} does not match any supported option"
		;;
	esac
	I=I+1
    done

    if [ "${HAS_R_FLAG}" == "true" ]; then
	cmac "~" -p "." -s "\#*\#"
    else
	cmac "~" -s "\#*\#" -p "." -d 0
    fi

    return 0
}

main "${@}"

