#!/bin/bash

readonly PROG_PATH=${0}
readonly PROG_DIR=${0%/*}
readonly PROG_NAME=$(basename $0)

notify() {
    echo "${PROG_NAME}: $1"
    return 0
}

print_usage() {

    echo "Usage: ${PROG_NAME} <file>"
    echo
    echo "Arguments:"
    echo " <file>             Kotlin file to compile; .kt"
    echo

    return 0
}

main() {

    declare -ri NUM_ARGS=1

    if [ "${1}" == "-h" ] || [ "${1}" == "--help" ]; then
	print_usage
	return 0
    fi

    if [ $# -lt ${NUM_ARGS} ]; then 
	notify "try '${PROG_NAME} -h' or '${PROG_NAME} --help' for more information"
	return 1
    fi
    
    declare KT_FILE=${1}
    declare COMPILED=${KT_FILE%.*}Kt
    
    notify "compiling ${KT_FILE}..."
    kotlinc ${KT_FILE}
    
    notify "running ${COMPILED}..."
    kotlin ${COMPILED}

    return 0
}

main "${@}"

