#!/bin/bash

readonly PROG_PATH=${0}
readonly PROG_DIR=${0%/*}
readonly PROG_NAME=$(basename $0)

notify() {
    echo "${PROG_NAME}: $1"
    return 0
}

print_usage() {

    echo "Usage: ${PROG_NAME} [options...]"
    echo
    echo "Options:"
    echo " -m, <message>      Sets the commit message; defaults to 'Synchronized with .gitignore file.'"

    return 0
}

main() {

    declare -ri NUM_ARGS=0

    if [ "${1}" == "-h" ] || [ "${1}" == "--help" ]; then
	print_usage
	return 0
    fi

    if [ $# -lt ${NUM_ARGS} ]; then 
	notify "try '${PROG_NAME} -h' or '${PROG_NAME} --help' for more information"
	return 1
    fi
    
    declare HAS_M_FLAG="false"
    declare M_FLAG="Synchronized with .gitignore file."

    declare -i I=$NUM_ARGS
    I=I+1
    while [ $I -le $# ]; do
	case ${!I} in
	    "-m")
		I=I+1
		HAS_M_FLAG="true"
		M_FLAG=${!I}
		;;
	    *)
		notify "${!I} does not match any supported option"
		;;
	esac
	I=I+1
    done

    git rm -r --cached .
    git add -A
    git commit -m "${M_FLAG}"

    return 0
}

main "${@}"