#!/bin/bash

readonly PROG_PATH=${0}
readonly PROG_DIR=${0%/*}
readonly PROG_NAME=$(basename $0)

notify() {
    echo "${PROG_NAME}: $1"
    return 0
}

print_usage() {

    echo "Usage: ${PROG_NAME} <arg1> <arg2> [options...]"
    echo
    echo "Arguments:"
    echo " <arg1>             Description 1"
    echo " <arg2>             Description 2"
    echo
    echo "Options:"
    echo " -a, <a_arg>        Specifies the a arg"
    echo " -b,                Activates xxx"

    return 0
}

main() {

    declare -ri NUM_ARGS=2

    if [ "${1}" == "-h" ] || [ "${1}" == "--help" ]; then
	print_usage
	return 0
    fi

    if [ $# -lt ${NUM_ARGS} ]; then 
	notify "try '${PROG_NAME} -h' or '${PROG_NAME} --help' for more information"
	return 1
    fi

    if [ $# -le ${NUM_ARGS} ]; then 
	notify "no default behaviour without any option(s)"
	return 1
    fi

    declare HAS_A_FLAG="false"
    declare A_FLAG=""
    declare HAS_B_FLAG="false"

    declare -i I=$NUM_ARGS
    I=I+1
    while [ $I -le $# ]; do
	case ${!I} in
	    "-a")
		I=I+1
		HAS_A_FLAG="true"
		A_FLAG=${!I}
		;;
	    "-b")
		HAS_B_FLAG="true"
		;;
	    *)
		notify "${!I} does not match any supported option"
		;;
	esac
	I=I+1
    done
    
    # <CODE HERE>

    return 0
}

main "${@}"

